#' Toy weekly admission history
#'
#' Synthetic weekly admission counts for one location, in the standard
#' hubverse target data shape. Covers 53 weeks before
#' `reference_date = 2024-12-21` plus 4 weeks of overlap with the
#' horizons in [admission_forecast], so the same series can also serve
#' as the `admission_history` argument of [fcast_census()].
#'
#' In a real workflow this comes from a hub's target time series, e.g.
#' `hubData::connect_target_timeseries()`.
#'
#' @format A tibble with columns `target_end_date`, `target`,
#'   `location`, `observation` (weekly admissions).
"admission_history"

#' Toy weekly admission quantile forecast
#'
#' Synthetic hubverse format admission quantile forecast for 4 weeks
#' after `reference_date = 2024-12-21`, paired with [admission_history].
#'
#' In a real workflow this comes from a forecasting hub, e.g.
#' `hubData::connect_hub() |> collect_hub()`.
#'
#' @format A tibble with the standard hubverse model output columns.
"admission_forecast"

#' Toy weekly census history
#'
#' Synthetic weekly census counts in the standard hubverse target data
#' shape, generated by convolving [admission_history] with a "true"
#' length of stay distribution (`negbin(mu = 2, k = 1.7)`). Pair with
#' [admission_history] as input to [fit_los()] or use as truth in
#' [score_census()].
#'
#' Hubs publish admissions truth, not census truth. In a real workflow
#' you supply census from your own hospital records.
#'
#' @format A tibble with columns `target_end_date`, `target`,
#'   `location`, `observation` (weekly census, not admissions).
"census_history"
